version: '3.8'

services:
  gateway:
    build: gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
      - db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shareIt
#      DB_HOST: db
#      DB_PORT: 5432
#      DB_NAME: shareIt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot
      TZ: "Europe/Moscow"

  db:
    image: postgres:13.7-alpine
    container_name: shareit-db
    ports:
      - "6432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: shareIt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot






